chore: update cmake make ocr optional
linuxdeepin/deepin-image-viewer pull request #128
Opened 2023-02-21 04:00 UTC by Decodetalkers

Log: cmake and ocr optional

2023-02-21 04:01 UTC, Decodetalkers commented
等下，我只是--build了下，怎么翻译也变化了

libdraw使用源的，不要在项目里面放了

2023-02-21 04:02 UTC, Decodetalkers commented
qtquick_compiler_add_resources(RCC_SOURCES ${RESOURCES}) 
这玩意要干掉，这个很快就会废弃了

2023-02-21 05:12 UTC, wineee commented
这个我改过一部分了，https://github.com/linuxdeepin/deepin-image-viewer/pull/127 我们重复了

2023-02-21 05:18 UTC, Decodetalkers commented
> 这个我改过一部分了，#127 我们重复了

libdraw应该用pkgconfig,这个在代码里面的应该直接扔掉才对

2023-02-21 05:23 UTC, wineee commented
> > 这个我改过一部分了，#127 我们重复了
> 
> libdraw应该用pkgconfig,这个在代码里面的应该直接扔掉才对

libraw 本来就是用的系统的，你删除的不是不是 libraw 本体，应该是插件吧？
https://github.com/LibRaw/LibRaw

2023-02-21 05:24 UTC, Decodetalkers commented
> 

哦，那我搞错了

2023-02-21 05:42 UTC, Decodetalkers commented
> > > 这个我改过一部分了，#127 我们重复了
> > 
> > 
> > libdraw应该用pkgconfig,这个在代码里面的应该直接扔掉才对
> 
> libraw 本来就是用的系统的，你删除的不是不是 libraw 本体，应该是插件吧？ https://github.com/LibRaw/LibRaw

那我先等你那个合并咯，你要不先处理libraw的

2023-02-21 06:02 UTC, wineee commented
ok， https://github.com/linuxdeepin/developer-center/issues/3786 这个也要改，以后单独搞个 pr 吧

2023-02-21 06:41 UTC, rb-union commented on src/main.cpp
>      engine.load(QUrl(QStringLiteral("qrc:/qml/main.qml")));
main.qml 被包括进宏

2023-03-01 06:16 UTC, zccrs requested changes

2023-03-01 06:16 UTC, zccrs commented on CMakeLists.txt
> +option(ENABLEOCR "Enable OCR" OFF)
应该在 debian/rules 中加参数设置为 ON

2023-03-01 06:21 UTC, wineee commented on CMakeLists.txt
> +option(ENABLEOCR "Enable OCR" OFF)
建议先
 review https://github.com/linuxdeepin/deepin-image-viewer/pull/127/files

这个是不完整的

2023-03-01 06:22 UTC, wineee commented on CMakeLists.txt
> +option(ENABLEOCR "Enable OCR" OFF)
修正文件权限等修改后面可以 rebase

2025-03-28 02:10 UTC, closed without merging